export const subCategories = {
  Mobiles: ["Realme", "Redmi", "OnePlus", "Samsung", "Oppo", "Vivo"],
  Fashion: [
    "Mens TopWear",
    "Mens BottomWear",
    "Mens FootWear",
    "Mens Ethnic Wear",
    "Womens TopWear",
    "Womens BottomWear",
    "Womens FootWear",
    "Womens Ethnic Wear",
  ],
  "Home & Furniture": [
    "Home Decor",
    "Kitchen & Dining",
    "Bedroom Furniture",
    "Living Room Furniture",
    "Workspace Furniture",
  ],
  Electronics: [
    "Laptops",
    "Desktops",
    "Camera",
    "Laptop Accessories",
    "Camera Accessories",
    "Mobile Accessories",
    "Speakers",
    "Smart Watches",
    "Health Care",
    "Gaming & Accessories",
  ],
  Appliances: [
    "Television",
    "Washing Machine",
    "Air Conditioner",
    "Kitchen Appliances",
    "Small Home Appliances",
  ],
  "Beauty & Cosmetics": [
    "Make Up",
    "Skin Care",
    "Hair Care",
    "Bath & Spa",
    "Deodrants & Perfumes",
  ],
};
